### ISSUE TITLE
Cannot find the file opencrimedeta

### ISSUE THREAD

**Issue by janesunflower** [MatthewDaws/SEPP#1]
Sorry, I cannot find the file opencrimedeta.

**Comment by MatthewDaws** [comment]
You just need to install this related project:

https://github.com/MatthewDaws/OpenCrimeData

Just clone or download it, and run

>  python setup.py install

**Comment by janesunflower** [comment]
So excited I am. Thank you very much.

________________________________
 Best wishes!

**Comment by janesunflower** [comment]
Excese me. I have some questions about the estimation of f and g in Appendix E, the questions are as follows:

1. The background kernel is two dimensional, and the form of f is the following equation?(Appendix B, fig.4)
[cid:_Foxmail.1@cdce3e9a-d459-c888-4ad4-3549104ddbe5]
2. f and g are estimated by KDE (fig.1), but I cannot get the result of g(tj − t i ,x j − x i ,y j − y i ) in fig.2 (tk), g in the code is also estimate by KDE? What is the kernal? How can I get it ?
3. Do you have the estimation process of the f and g in Appendix E?
4.  "we estimate f as a “weighted KDE” using the weights (p j,j ) " (fig.1), but the weights are set None in the fig.3, and  the annotation is "- `w_i` is a set of "weights", by default :math:`1/N` for all `i`.", the P-matrx is not mentioned.




[cid:_Foxmail.1@9184b228-6cca-f041-595f-3927f8b6e162]
fig.1

[cid:_Foxmail.1@59151797-b8a2-06aa-8019-64632ded88a3]
fig.2

[cid:_Foxmail.1@159c4e89-892d-7fbe-2990-2565e1dc55d4]

fig.3

[cid:_Foxmail.1@1fbe2659-3a64-a51e-2dc5-08ba4e869ec8]
fig.4







________________________________
 Best wishes!

From: jane.mjy@hotmail.com<mailto:jane.mjy@hotmail.com>
Date: 2018-07-19 15:58
To: MatthewDaws/SEPP<mailto:reply@reply.github.com>; MatthewDaws/SEPP<mailto:SEPP@noreply.github.com>
CC: Author<mailto:author@noreply.github.com>
Subject: Re: Re: [MatthewDaws/SEPP] Cannot find the file opencrimedeta (#1)
    So excited I am. Thank you very much.

________________________________
 Best wishes!
