### ISSUE TITLE
What‘s the difference between points and score_points?

### ISSUE THREAD

**Issue by janesunflower** [MatthewDaws/SEPP#2]
What‘s the difference between **points** and **score_points** in _def load(side, start, end)_ and  _def load_score_data(geo, start, end)_ of \notebooks\predictions\_making predictions 2.ipynb_?

**Comment by MatthewDaws** [comment]
Well, read the code!

    grid, points, geo = load("North", np.datetime64("2016-01-01"), np.datetime64("2016-10-01"))
    score_points = load_score_data(geo, np.datetime64("2016-01-01"), np.datetime64("2017-01-01"))

So the difference is the time range selected.  The idea is that we "train" the model on date to September.  This fixes the parameters in the model.  We then make predictions for each day in October to December, using the data up to the day in question, and "predicting" the next day.  This is handled by the `open_cp` code.

You could retrain the model each time on all the data you have.  But this _should_ be unnecessary: the structure of the model itself is meant to take account of short-term changes, retraining on data from very close time-ranges should not change the parameters.
